project_id = "ikbexcebcpmomfxraflz"

[functions.create-payment-intent]
verify_jwt = true

[functions.get-quote-by-token]
verify_jwt = false

[functions.update-catalog-pdf]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.check-catalog-limits]
verify_jwt = true

[functions.send-quote-accepted-email]
verify_jwt = false

[functions.send-quote-notification]
verify_jwt = false

[functions.track-catalog-view]
verify_jwt = false

[functions.openpay-webhook]
verify_jwt = false

[functions.tracking-events]
verify_jwt = false

[functions.generate-catalog-feed]
verify_jwt = false
